### ISSUE TITLE
convert 'open' tasks in Lug-Ulm wiki to issues in github

### ISSUE THREAD

**Issue by mi-hol** [stefanbaur/grannophone#1]
To engage with community and allow for parallel work on issue resolution a wiki is not a good tool. 
Therefore I'd suggest to transfer/convert the "work-in-progress" (WIP) [part of wiki](http://lugulm.de/dokuwiki/doku.php?id=grannophone) to issues in github.

This avoids issues caused by lacking permissions to write to Lug-Ulm wiki and is a simple quality control process for content published on  current Lug-Ulm wiki. 
Maybe in a next step transfer of all Lug-Ulm wiki content might be desirable to github too.

**Comment by stefanbaur** [comment]
Hi, this is just to let you know that your comment has been noticed by me. I am currently a bit overwhelmed by the feedback after the Grannophone was mentioned on heise -- especially as it is only a personal side project, not my day job. It may take a while until I get to come up with a meaningful reply. Sorry.

**Comment by stefanbaur** [comment]
Hi. Unfortunately, some personal issues on my end delayed work on the Grannophone project. However, I am now trying to pick up where I left. I have finally been able to set up a (German-language) mailing list for it. If you happen to speak/understand German, you might want to subscribe there. It's currently the second link from the bottom on this page: https://www.grannophone.de/

**Comment by mi-hol** [comment]
closing due to lack of interest
