### ISSUE TITLE
Software idea

### ISSUE THREAD

**Issue by probonopd** [stefanbaur/grannophone#3]
Great project idea!

Please keep it super simple for the non-technical user. Have been looking for somehting like this since quite a while.

Check out https://github.com/probonopd/OpenPhone, my open source desk telephone implemented in Python and pjsua. That one is not enabled for video yet, but maybe it can serve as an inspiration for implementing the software part of this project.

**Comment by stefanbaur** [comment]
Hi, this is just to let you know that your comment has been noticed by me. I am currently a bit overwhelmed by the feedback after the Grannophone was mentioned on heise -- especially as it is only a personal side project, not my day job. It may take a while until I get to come up with a meaningful reply. Sorry.

**Comment by stefanbaur** [comment]
Hi. Unfortunately, some personal issues on my end delayed work on the Grannophone project. However, I am now trying to pick up where I left. I have finally been able to set up a (German-language) mailing list for it. If you happen to speak/understand German, you might want to subscribe there. It's currently the second link from the bottom on this page: https://www.grannophone.de/
